---
driver:
  name: podman
platforms:
  - name: tox
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - destroyr
role_name_check: 1